### Fire Incidents

In [193]:
import pandas as pd

path = "...FDNY\\"

df = pd.read_csv(path + "Fire_Incident_Dispatch_Data_2025.csv", low_memory=False)

In [194]:
pd.set_option('chained_assignment', None)

df["COMMUNITYDISTRICT"] = df["COMMUNITYDISTRICT"].astype(str)
#df["COMMUNITYDISTRICT"] = df["COMMUNITYDISTRICT"].astype(int)
#df["COMMUNITYDISTRICT"] = df["COMMUNITYDISTRICT"].astype(str)
print (len(df))
df = df[df["COMMUNITYDISTRICT"] != 'nan'].reset_index(drop=True)
print (len(df))

df["COMMUNITYDISTRICT"] = df["COMMUNITYDISTRICT"].str.split(".").str[0]


cd = sorted(list(set(df["COMMUNITYDISTRICT"].tolist() )))
print (len(cd))
#cd

211774
199744
71

In [195]:
df["INCIDENT_CLASSIFICATION"] = df["INCIDENT_CLASSIFICATION"].astype(str)

ic = (list(set(df["INCIDENT_CLASSIFICATION"].tolist() )))

#for c in ic:
#    print (c)

#df["INCIDENT_CLASSIFICATION2"] = df["INCIDENT_CLASSIFICATION"].str.split(" - ").str[0].reset_index(drop=True)

df["INCIDENT_CLASSIFICATION2"] = (
    df["INCIDENT_CLASSIFICATION"]
    .str.split(r"\s-\s", regex=True)
    .str[0]
    .str.strip()
)

#df["INCIDENT_CLASSIFICATION2"] = df["INCIDENT_CLASSIFICATION2"].astype(str)

ic = (list(set(df["INCIDENT_CLASSIFICATION2"].tolist() )))

In [196]:
df2 = df[["COMMUNITYDISTRICT", "INCIDENT_CLASSIFICATION2", "INCIDENT_RESPONSE_SECONDS_QY", "INCIDENT_TRAVEL_TM_SECONDS_QY" ]]

df2["COMMUNITYDISTRICT"] = df2["COMMUNITYDISTRICT"].astype(str)


dummies = pd.get_dummies(df2["INCIDENT_CLASSIFICATION2"], prefix="IC").astype(int)
df2 = pd.concat([df2, dummies], axis=1)

df2 = df2.rename(columns={"IC_Multiple Dwelling 'A'": "IC_Multiple Dwelling A", })

Create Dataframe to Merge with Shapefile

In [197]:
subset = ['COMMUNITYDISTRICT', 'INCIDENT_RESPONSE_SECONDS_QY', 'INCIDENT_TRAVEL_TM_SECONDS_QY', 'IC_Medical', 'IC_Assist Civilian', 'IC_Utility Emergency', 'IC_Alarm System', 'IC_Elevator Emergency',
         'IC_Odor', 'IC_Non-Medical MFA', 'IC_Multiple Dwelling A', 'IC_Carbon Monoxide', 'IC_Vehicle Accident', 'IC_Private Dwelling Fire']
df3 = df2[subset]

Get centroid of the community district

In [198]:
import geopandas as gpd

pathshape = "C:\\Users\\MehriD01\\OneDrive - New York City Housing Authority\\Documents\\FDNY\\nycd_26a\\"

# Load shapefile
gdf = gpd.read_file(pathshape + "nycd.shp")

# project to a projected CRS
gdf_proj = gdf.to_crs(epsg=2263)

# calculate centroid there
gdf_proj["centroid"] = gdf_proj.geometry.centroid

# convert centroid back to lat/lon
centroids = gdf_proj.set_geometry("centroid").to_crs(epsg=4326)

gdf["lon"] = centroids.geometry.x
gdf["lat"] = centroids.geometry.y

gdf = gdf[["BoroCD", "lon", "lat"]]

gdf["BoroCD"] = gdf["BoroCD"].astype(str)

Groupby

In [199]:
df4 = df3[['COMMUNITYDISTRICT', 'IC_Medical', 'IC_Assist Civilian', 'IC_Utility Emergency', 'IC_Alarm System', 'IC_Elevator Emergency',
         'IC_Odor', 'IC_Non-Medical MFA', 'IC_Multiple Dwelling A', 'IC_Carbon Monoxide', 'IC_Vehicle Accident', 'IC_Private Dwelling Fire'] ]

df4["COMMUNITYDISTRICT"] = df4["COMMUNITYDISTRICT"].astype(str)

df4G = df4.groupby(['COMMUNITYDISTRICT']).sum()
df4G = df4G.add_suffix('').reset_index()

df4G

,COMMUNITYDISTRICT,IC_Medical,IC_Assist Civilian,IC_Utility Emergency,IC_Alarm System,IC_Elevator Emergency,IC_Odor,IC_Non-Medical MFA,IC_Multiple Dwelling A,IC_Carbon Monoxide,IC_Vehicle Accident,IC_Private Dwelling Fire
0,101,933,122,93,402,166,68,67,23,21,8,2
1,102,1413,175,173,481,119,155,65,52,41,15,4
2,103,2879,414,515,337,512,211,94,129,112,17,1
3,104,2478,300,222,502,276,138,135,71,54,36,1
4,105,2917,293,209,1140,314,125,191,28,29,22,1
...,...,...,...,...,...,...,...,...,...,...,...,...
66,484,4,0,0,0,0,0,0,0,0,0,0
67,501,2446,454,294,170,160,118,68,44,79,110,121
68,502,1599,269,170,173,32,74,24,16,60,110,88
69,503,1361,281,150,73,8,86,23,9,68,72,117
70,595,2,0,0,0,0,1,2,0,0,0,0

Merge lat/lon and incident response times

In [200]:
gdfDic = gdf.set_index('BoroCD')['lat'].to_dict()
df4G["lat"] = df4G["COMMUNITYDISTRICT"].map(gdfDic)

gdfDic = gdf.set_index('BoroCD')['lon'].to_dict()
df4G["lon"] = df4G["COMMUNITYDISTRICT"].map(gdfDic)

Add Population by Community District

In [201]:
path

'C:\\Users\\MehriD01\\OneDrive - New York City Housing Authority\\Documents\\FDNY\\'

In [202]:
dp = pd.read_csv(path + "New_York_City_Population_By_Community_Districts_20260414.csv")
dp["CD Number"] = dp["CD Number"].astype(str)
dp["CD Number"] = dp["CD Number"].str.split(".").str[0]
dp = dp[dp["CD Number"] != 'nan']

dp['Borough2'] = dp['Borough']

dp['Borough2'] = dp['Borough2'].str.replace('Bronx', '2')
dp['Borough2'] = dp['Borough2'].str.replace('Manhattan', '1')
dp['Borough2'] = dp['Borough2'].str.replace('Brooklyn', '3')
dp['Borough2'] = dp['Borough2'].str.replace('Queens', '4')
dp['Borough2'] = dp['Borough2'].str.replace('Staten Island', '5')

dp['boro_cd'] = dp['Borough2'].astype(str) + dp['CD Number'].astype(str).str.zfill(2)

dp['2010 Population'] = dp['2010 Population'].str.replace(',', '')

dp['2010 Population'] = dp['2010 Population'].astype(int)

In [203]:
dp

,Borough,CD Number,CD Name,1970 Population,1980 Population,1990 Population,2000 Population,2010 Population,Borough2,boro_cd
0,Bronx,1,"Melrose, Mott Haven, Port Morris","138,557","78,441","77,214","82,159",91497,2,201
1,Bronx,2,"Hunts Point, Longwood","99,493","34,399","39,443","46,824",52246,2,202
2,Bronx,3,"Morrisania, Crotona Park East","150,636","53,635","57,162","68,574",79762,2,203
3,Bronx,4,"Highbridge, Concourse Village","144,207","114,312","119,962","139,563",146441,2,204
4,Bronx,5,"University Hts., Fordham, Mt. Hope","121,807","107,995","118,435","128,313",128200,2,205
5,Bronx,6,"East Tremont, Belmont","114,137","65,016","68,061","75,688",83268,2,206
6,Bronx,7,"Bedford Park, Norwood, Fordham","113,764","116,827","128,588","141,411",139286,2,207
7,Bronx,8,"Riverdale, Kingsbridge, Marble Hill","103,543","98,275","97,030","101,332",101731,2,208
8,Bronx,9,"Soundview, Parkchester","166,442","167,627","155,970","167,859",172298,2,209
9,Bronx,10,"Throgs Nk., Co-op City, Pelham Bay","84,948","106,516","108,093","115,948",120392,2,210
10,Bronx,11,"Pelham Pkwy, Morris Park, Laconia","105,980","99,080","97,842","110,706",113232,2,211
11,Bronx,12,"Wakefield, Williamsbridge","135,010","128,226","129,620","149,077",152344,2,212
12,Brooklyn,1,"Williamsburg, Greenpoint","179,390","142,942","155,972","160,338",173083,3,301
13,Brooklyn,2,"Brooklyn Heights, Fort Greene","110,221","92,732","94,534","98,620",99617,3,302
14,Brooklyn,3,Bedford Stuyvesant,"203,380","133,379","138,696","143,867",152985,3,303
15,Brooklyn,4,Bushwick,"137,902","92,497","102,572","104,358",112634,3,304
16,Brooklyn,5,"East New York, Starrett City","170,791","154,931","161,350","173,198",182896,3,305
17,Brooklyn,6,"Park Slope, Carroll Gardens","138,933","110,228","102,724","104,054",104709,3,306
18,Brooklyn,7,"Sunset Park, Windsor Terrace","111,607","98,567","102,553","120,063",126230,3,307
19,Brooklyn,8,Crown Heights North,"121,821","88,796","96,400","96,076",96317,3,308
20,Brooklyn,9,"Crown Heights South, Wingate","101,047","96,669","110,715","104,014",98429,3,309
21,Brooklyn,10,"Bay Ridge, Dyker Heights","129,822","118,187","110,612","122,542",124491,3,310
22,Brooklyn,11,"Bensonhurst, Bath Beach","170,119","155,072","149,994","172,129",181981,3,311
23,Brooklyn,12,"Borough Park, Ocean Parkway","166,301","155,899","160,018","185,046",191382,3,312
24,Brooklyn,13,"Coney Island, Brighton Beach","97,750","100,030","102,596","106,120",104278,3,313
25,Brooklyn,14,"Flatbush, Midwood","137,041","143,859","159,825","168,806",160664,3,314
26,Brooklyn,15,"Sheepshead Bay, Gerritsen Beach","164,815","149,572","143,477","160,319",159650,3,315
27,Brooklyn,16,"Brownsville, Ocean Hill","122,589","73,801","84,923","85,343",86468,3,316
28,Brooklyn,17,"East Flatbush, Rugby, Farragut","149,496","154,596","161,261","165,753",155252,3,317
29,Brooklyn,18,"Canarsie, Flatlands","188,643","169,092","162,428","194,653",193543,3,318
30,Manhattan,1,"Battery Park City, Tribeca","7,706","15,918","25,366","34,420",60978,1,101
31,Manhattan,2,"Greenwich Village, Soho","84,337","87,069","94,105","93,119",90016,1,102
32,Manhattan,3,"Lower East Side, Chinatown","181,845","154,848","161,617","164,407",163277,1,103
33,Manhattan,4,"Chelsea, Clinton","83,601","82,164","84,431","87,479",103245,1,104
34,Manhattan,5,Midtown Business District,"31,076","39,544","43,507","44,028",51673,1,105
35,Manhattan,6,"Stuyvesant Town, Turtle Bay","122,465","127,554","133,748","136,152",142745,1,106
36,Manhattan,7,"West Side, Upper West Side","212,422","206,669","210,993","207,699",209084,1,107
37,Manhattan,8,Upper East Side,"200,851","204,305","210,880","217,063",219920,1,108
38,Manhattan,9,"Manhattanville, Hamilton Heights","113,606","103,038","106,978","111,724",110193,1,109
39,Manhattan,10,Central Harlem,"159,267","105,641","99,519","107,109",115723,1,110
40,Manhattan,11,East Harlem,"154,662","114,569","110,508","117,743",120511,1,111
41,Manhattan,12,"Washington Heights, Inwood","180,561","179,941","198,192","208,414",190020,1,112
42,Queens,1,"Astoria, Long Island City","185,925","185,198","188,549","211,220",191105,4,401
43,Queens,2,"Sunnyside, Woodside","95,073","88,927","94,845","109,920",113200,4,402
44,Queens,3,"Jackson Heights, North Corona","123,635","122,090","128,924","169,083",171576,4,403
45,Queens,4,"Elmhurst, South Corona","108,233","118,430","137,023","167,005",172598,4,404
46,Queens,5,"Ridgewood, Glendale, Maspeth","161,022","150,142","149,126","165,911",169190,4,405
47,Queens,6,"Forest Hills, Rego Park","120,429","112,245","106,996","115,967",113257,4,406
48,Queens,7,"Flushing, Bay Terrace","207,589","204,785","220,508","242,952",247354,4,407
49,Queens,8,"Fresh Meadows, Briarwood","142,468","125,312","132,101","146,594",151107,4,408
50,Queens,9,"Woodhaven, Richmond Hill","110,367","109,505","112,151","141,608",143317,4,409
51,Queens,10,"Ozone Park, Howard Beach","113,857","105,651","107,768","127,274",122396,4,410
52,Queens,11,"Bayside, Douglaston, Little Neck","127,883","110,963","108,056","116,404",116431,4,411
53,Queens,12,"Jamaica, St. Albans, Hollis","206,639","189,383","201,293","223,602",225919,4,412
54,Queens,13,"Queens Village, Rosedale","184,647","173,178","177,535","196,284",188593,4,413
55,Queens,14,"The Rockaways, Broad Channel","98,228","100,592","100,596","106,686",114978,4,414
56,Staten Island,1,"Stapleton, Port Richmond","135,875","138,489","137,806","162,609",175756,5,501
57,Staten Island,2,"New Springville, South Beach","85,985","105,128","113,944","127,071",132003,5,502
58,Staten Island,3,"Tottenville, Woodrow, Great Kills","72,815","108,249","126,956","152,908",160209,5,503

Merge

In [205]:
dpDic = dp.set_index('boro_cd')['2010 Population'].to_dict()
df4G["2010 Population"] = df4G["COMMUNITYDISTRICT"].map(dpDic)

dpDic = dp.set_index('boro_cd')['CD Name'].to_dict()
df4G["Community District Name"] = df4G["COMMUNITYDISTRICT"].map(dpDic)

dpDic = dp.set_index('boro_cd')['Borough'].to_dict()
df4G["Borough"] = df4G["COMMUNITYDISTRICT"].map(dpDic)

print (len(df4G))
df4G["2010 Population"] = df4G["2010 Population"].astype(str)
df4G = df4G[df4G["2010 Population"] != 'nan'].reset_index(drop=True)
df4G["2010 Population"] = df4G["2010 Population"].astype(int)
print (len(df4G))


df4G["Medical Norm"] = (df4G["IC_Medical"]/df4G["2010 Population"] ) * 100000
df4G["Assist Civilian Norm"] = (df4G["IC_Assist Civilian"]/df4G["2010 Population"] ) * 100000
df4G["Utility Emergency Norm"] = (df4G["IC_Utility Emergency"]/df4G["2010 Population"] ) * 100000
df4G["Private Dwelling Fire Norm"] = (df4G["IC_Private Dwelling Fire"]/df4G["2010 Population"] ) * 100000

df4G["Medical Norm"] = df4G["Medical Norm"].round(0)
df4G["Assist Civilian Norm"] = df4G["Assist Civilian Norm"].round(0)
df4G["Utility Emergency Norm"] = df4G["Utility Emergency Norm"].round(0)
df4G["Private Dwelling Fire Norm"] = df4G["Private Dwelling Fire Norm"].round(0)

59
59

In [206]:
#df4G.to_csv(path + "test.csv", index=False)

Add Response Time

In [207]:
dr = df2[["COMMUNITYDISTRICT", "INCIDENT_RESPONSE_SECONDS_QY"]]

print (len(dr))

dr["INCIDENT_RESPONSE_SECONDS_QY"] = dr["INCIDENT_RESPONSE_SECONDS_QY"].astype(str)
dr = dr[dr["INCIDENT_RESPONSE_SECONDS_QY"] != 'nan']
dr["INCIDENT_RESPONSE_SECONDS_QY"] = dr["INCIDENT_RESPONSE_SECONDS_QY"].str.replace(',', '')
dr["INCIDENT_RESPONSE_SECONDS_QY"] = dr["INCIDENT_RESPONSE_SECONDS_QY"].astype(int)

print (len(dr))


drG = dr.groupby(['COMMUNITYDISTRICT']).mean().round(0)
drG = drG.add_suffix('').reset_index()

drDic = drG.set_index('COMMUNITYDISTRICT')['INCIDENT_RESPONSE_SECONDS_QY'].to_dict()
df4G["Response Time"] = df4G["COMMUNITYDISTRICT"].map(drDic)
df4G["Response Time"] = (df4G["Response Time"]/60).round(2)


dr = df2[["COMMUNITYDISTRICT",  "INCIDENT_TRAVEL_TM_SECONDS_QY"]]

dr["INCIDENT_TRAVEL_TM_SECONDS_QY"] = dr["INCIDENT_TRAVEL_TM_SECONDS_QY"].astype(str)
dr = dr[dr["INCIDENT_TRAVEL_TM_SECONDS_QY"] != 'nan']
dr["INCIDENT_TRAVEL_TM_SECONDS_QY"] = dr["INCIDENT_TRAVEL_TM_SECONDS_QY"].str.replace(',', '')
dr["INCIDENT_TRAVEL_TM_SECONDS_QY"] = dr["INCIDENT_TRAVEL_TM_SECONDS_QY"].astype(int)

print (len(dr))

drG = dr.groupby(['COMMUNITYDISTRICT']).mean().round(0)
drG = drG.add_suffix('').reset_index()

drDic = drG.set_index('COMMUNITYDISTRICT')['INCIDENT_TRAVEL_TM_SECONDS_QY'].to_dict()
df4G["Travel Time"] = df4G["COMMUNITYDISTRICT"].map(drDic)
df4G["Travel Time"] = (df4G["Travel Time"]/60).round(2)

199744
151986
151986

In [208]:
df4G

,COMMUNITYDISTRICT,IC_Medical,IC_Assist Civilian,IC_Utility Emergency,IC_Alarm System,IC_Elevator Emergency,IC_Odor,IC_Non-Medical MFA,IC_Multiple Dwelling A,IC_Carbon Monoxide,...,lon,2010 Population,Community District Name,Borough,Medical Norm,Assist Civilian Norm,Utility Emergency Norm,Private Dwelling Fire Norm,Response Time,Travel Time
0,101,933,122,93,402,166,68,67,23,21,...,-74.011997,60978,"Battery Park City, Tribeca",Manhattan,1530.0,200.0,153.0,3.0,5.77,5.20
1,102,1413,175,173,481,119,155,65,52,41,...,-74.001559,90016,"Greenwich Village, Soho",Manhattan,1570.0,194.0,192.0,4.0,5.22,4.63
2,103,2879,414,515,337,512,211,94,129,112,...,-73.985541,163277,"Lower East Side, Chinatown",Manhattan,1763.0,254.0,315.0,1.0,5.98,5.43
3,104,2478,300,222,502,276,138,135,71,54,...,-73.997537,103245,"Chelsea, Clinton",Manhattan,2400.0,291.0,215.0,1.0,6.50,5.85
4,105,2917,293,209,1140,314,125,191,28,29,...,-73.984057,51673,Midtown Business District,Manhattan,5645.0,567.0,404.0,2.0,6.47,5.82
5,106,1620,188,184,410,169,100,74,53,37,...,-73.974576,142745,"Stuyvesant Town, Turtle Bay",Manhattan,1135.0,132.0,129.0,0.0,6.02,5.42
6,107,2125,271,316,347,281,174,89,97,93,...,-73.976126,209084,"West Side, Upper West Side",Manhattan,1016.0,130.0,151.0,0.0,6.23,5.58
7,108,1778,255,269,415,198,201,61,82,70,...,-73.955718,219920,Upper East Side,Manhattan,808.0,116.0,122.0,3.0,6.63,5.88
8,109,1363,217,296,179,213,113,45,77,38,...,-73.955030,110193,"Manhattanville, Hamilton Heights",Manhattan,1237.0,197.0,269.0,0.0,6.05,5.37
9,110,2458,375,522,270,597,216,119,169,82,...,-73.944736,115723,Central Harlem,Manhattan,2124.0,324.0,451.0,0.0,6.57,5.77
10,111,2958,337,629,371,644,191,161,170,113,...,-73.934979,120511,East Harlem,Manhattan,2455.0,280.0,522.0,2.0,6.20,5.50
11,112,2512,283,410,194,216,188,75,129,55,...,-73.931522,190020,"Washington Heights, Inwood",Manhattan,1322.0,149.0,216.0,0.0,6.42,5.72
12,201,3044,544,500,384,602,130,88,140,70,...,-73.916469,91497,"Melrose, Mott Haven, Port Morris",Bronx,3327.0,595.0,546.0,7.0,6.23,5.52
13,202,1208,166,148,119,49,76,30,50,21,...,-73.887878,52246,"Hunts Point, Longwood",Bronx,2312.0,318.0,283.0,4.0,6.50,5.75
14,203,1959,350,410,256,374,131,67,124,50,...,-73.898650,79762,"Morrisania, Crotona Park East",Bronx,2456.0,439.0,514.0,6.0,6.58,5.83
15,204,2637,387,418,262,272,143,104,158,52,...,-73.920797,146441,"Highbridge, Concourse Village",Bronx,1801.0,264.0,285.0,1.0,6.90,6.13
16,205,2614,346,381,297,323,138,69,174,45,...,-73.909580,128200,"University Hts., Fordham, Mt. Hope",Bronx,2039.0,270.0,297.0,6.0,6.73,5.97
17,206,2033,286,303,304,161,105,98,127,47,...,-73.887530,83268,"East Tremont, Belmont",Bronx,2442.0,343.0,364.0,5.0,6.35,5.55
18,207,2425,260,303,197,233,113,81,145,46,...,-73.891457,139286,"Bedford Park, Norwood, Fordham",Bronx,1741.0,187.0,218.0,4.0,7.37,6.47
19,208,1158,157,216,147,142,84,38,59,39,...,-73.906297,101731,"Riverdale, Kingsbridge, Marble Hill",Bronx,1138.0,154.0,212.0,16.0,7.27,6.52
20,209,2343,390,365,210,418,133,122,119,66,...,-73.861656,172298,"Soundview, Parkchester",Bronx,1360.0,226.0,212.0,13.0,7.45,6.70
21,210,1397,222,268,149,90,156,61,69,76,...,-73.821813,120392,"Throgs Nk., Co-op City, Pelham Bay",Bronx,1160.0,184.0,223.0,21.0,6.62,5.92
22,211,1698,265,269,142,133,111,69,56,40,...,-73.852775,113232,"Pelham Pkwy, Morris Park, Laconia",Bronx,1500.0,234.0,238.0,38.0,7.17,6.43
23,212,2186,390,355,223,197,159,116,103,83,...,-73.851495,152344,"Wakefield, Williamsbridge",Bronx,1435.0,256.0,233.0,43.0,7.15,6.37
24,301,2063,287,297,512,330,166,97,112,116,...,-73.947170,173083,"Williamsburg, Greenpoint",Brooklyn,1192.0,166.0,172.0,4.0,5.30,4.72
25,302,2052,286,236,526,281,131,110,81,83,...,-73.978725,99617,"Brooklyn Heights, Fort Greene",Brooklyn,2060.0,287.0,237.0,21.0,5.55,4.93
26,303,2504,361,478,304,345,148,110,152,126,...,-73.940562,152985,Bedford Stuyvesant,Brooklyn,1637.0,236.0,312.0,21.0,4.98,4.47
27,304,1633,150,177,234,36,105,40,54,71,...,-73.916834,112634,Bushwick,Brooklyn,1450.0,133.0,157.0,14.0,4.65,4.15
28,305,3512,385,341,386,242,135,166,122,90,...,-73.879713,182896,"East New York, Starrett City",Brooklyn,1920.0,211.0,186.0,19.0,6.02,5.37
29,306,1234,191,258,248,131,138,58,50,97,...,-73.994450,104709,"Park Slope, Carroll Gardens",Brooklyn,1179.0,182.0,246.0,37.0,5.37,4.80
30,307,1161,188,128,153,47,76,54,22,40,...,-74.001058,126230,"Sunset Park, Windsor Terrace",Brooklyn,920.0,149.0,101.0,10.0,5.40,4.92
31,308,1387,253,244,139,105,111,56,72,93,...,-73.946600,96317,Crown Heights North,Brooklyn,1440.0,263.0,253.0,18.0,5.17,4.55
32,309,1154,179,180,151,154,92,114,73,48,...,-73.946924,98429,"Crown Heights South, Wingate",Brooklyn,1172.0,182.0,183.0,17.0,5.88,5.22
33,310,1174,177,98,80,31,110,39,34,34,...,-74.023466,124491,"Bay Ridge, Dyker Heights",Brooklyn,943.0,142.0,79.0,20.0,5.33,4.78
34,311,1474,176,128,70,41,71,32,31,26,...,-73.993638,181981,"Bensonhurst, Bath Beach",Brooklyn,810.0,97.0,70.0,13.0,5.63,5.12
35,312,1067,191,133,250,63,79,68,54,52,...,-73.983259,191382,"Borough Park, Ocean Parkway",Brooklyn,558.0,100.0,69.0,37.0,5.67,5.08
36,313,1652,215,186,128,268,67,45,46,31,...,-73.982151,104278,"Coney Island, Brighton Beach",Brooklyn,1584.0,206.0,178.0,14.0,5.98,5.37
37,314,1578,244,228,171,164,128,69,96,59,...,-73.959118,160664,"Flatbush, Midwood",Brooklyn,982.0,152.0,142.0,25.0,5.60,4.98
38,315,1411,217,175,196,108,101,53,44,60,...,-73.949852,159650,"Sheepshead Bay, Gerritsen Beach",Brooklyn,884.0,136.0,110.0,43.0,5.85,5.23
39,316,2300,227,314,175,217,84,132,111,65,...,-73.910943,86468,"Brownsville, Ocean Hill",Brooklyn,2660.0,263.0,363.0,19.0,5.53,4.98
40,317,2045,277,343,201,107,111,88,91,96,...,-73.933820,155252,"East Flatbush, Rugby, Farragut",Brooklyn,1317.0,178.0,221.0,39.0,5.45,4.80
41,318,1879,340,292,200,120,105,103,41,127,...,-73.914024,193543,"Canarsie, Flatlands",Brooklyn,971.0,176.0,151.0,68.0,6.28,5.57
42,401,2017,363,336,253,200,209,69,73,87,...,-73.913357,191105,"Astoria, Long Island City",Queens,1055.0,190.0,176.0,9.0,6.70,6.07
43,402,1197,189,119,245,78,86,39,43,27,...,-73.923018,113200,"Sunnyside, Woodside",Queens,1057.0,167.0,105.0,14.0,6.15,5.50
44,403,1411,167,92,88,38,56,30,33,19,...,-73.876938,171576,"Jackson Heights, North Corona",Queens,822.0,97.0,54.0,12.0,6.37,5.80
45,404,1346,160,100,119,78,49,32,49,13,...,-73.871496,172598,"Elmhurst, South Corona",Queens,780.0,93.0,58.0,10.0,5.85,5.23
46,405,1316,259,160,149,12,77,32,17,54,...,-73.890535,169190,"Ridgewood, Glendale, Maspeth",Queens,778.0,153.0,95.0,21.0,5.58,5.05
47,406,914,116,92,123,57,56,22,37,34,...,-73.851349,113257,"Forest Hills, Rego Park",Queens,807.0,102.0,81.0,17.0,6.55,5.93
48,407,2059,307,221,252,125,143,66,41,43,...,-73.816036,247354,"Flushing, Bay Terrace",Queens,832.0,124.0,89.0,30.0,6.52,5.80
49,408,1271,196,195,132,57,72,64,53,54,...,-73.797355,151107,"Fresh Meadows, Briarwood",Queens,841.0,130.0,129.0,30.0,6.15,5.48
50,409,1484,208,106,83,21,66,78,21,34,...,-73.839065,143317,"Woodhaven, Richmond Hill",Queens,1035.0,145.0,74.0,32.0,6.03,5.48
51,410,1318,215,93,96,6,68,36,19,40,...,-73.832737,122396,"Ozone Park, Howard Beach",Queens,1077.0,176.0,76.0,54.0,6.03,5.48
52,411,678,147,135,94,12,95,20,14,28,...,-73.759183,116431,"Bayside, Douglaston, Little Neck",Queens,582.0,126.0,116.0,41.0,5.70,5.13
53,412,3359,473,305,287,107,115,78,87,114,...,-73.778435,225919,"Jamaica, St. Albans, Hollis",Queens,1487.0,209.0,135.0,76.0,5.80,5.22
54,413,1915,334,202,191,8,85,54,6,132,...,-73.737346,188593,"Queens Village, Rosedale",Queens,1015.0,177.0,107.0,93.0,6.20,5.55
55,414,1672,340,225,124,193,87,49,73,59,...,-73.810280,114978,"The Rockaways, Broad Channel",Queens,1454.0,296.0,196.0,49.0,6.28,5.55
56,501,2446,454,294,170,160,118,68,44,79,...,-74.120493,175756,"Stapleton, Port Richmond",Staten Island,1392.0,258.0,167.0,69.0,5.35,4.80
57,502,1599,269,170,173,32,74,24,16,60,...,-74.141803,132003,"New Springville, South Beach",Staten Island,1211.0,204.0,129.0,67.0,5.88,5.37
58,503,1361,281,150,73,8,86,23,9,68,...,-74.190299,160209,"Tottenville, Woodrow, Great Kills",Staten Island,850.0,175.0,94.0,73.0,6.13,5.60

Add borough to cd name

In [209]:
df4G["Community District Name"] = df4G["Community District Name"] + ", " + df4G["Borough"]

In [210]:
df4G.to_csv(path + "Fire Dispatch Data 2025.csv", index=False)

Mean and Standard Deviation

In [211]:
mean_val = df4G['Response Time'].mean()
print (mean_val)
std_val = df4G['Response Time'].std()
print (std_val)

6.089661016949153
0.6026978602048456

In [192]:
df4G.dtypes

COMMUNITYDISTRICT            object
IC_Medical                    int32
IC_Assist Civilian            int32
IC_Utility Emergency          int32
IC_Alarm System               int32
IC_Elevator Emergency         int32
IC_Odor                       int32
IC_Non-Medical MFA            int32
IC_Multiple Dwelling A        int32
IC_Carbon Monoxide            int32
IC_Vehicle Accident           int32
IC_Private Dwelling Fire      int32
lat                         float64
lon                         float64
2010 Population               int32
Community District Name      object
Borough                      object
Medical Norm                float64
Assist Civilian Norm        float64
Utility Emergency Norm      float64
Private Dwelling Fire       float64
Response Time               float64
Travel Time                 float64
dtype: object

In [22]:
cols = df2.columns
for c in cols:
    print (c)

COMMUNITYDISTRICT
INCIDENT_CLASSIFICATION2
INCIDENT_RESPONSE_SECONDS_QY
INCIDENT_TRAVEL_TM_SECONDS_QY
IC_Abandoned Derelict Vehicle Fire
IC_Alarm System
IC_Assist Civilian
IC_Automobile Fire
IC_Brush Fire
IC_Carbon Monoxide
IC_Church Fire
IC_Defective Oil Burner
IC_Demolition Debris or Rubbish Fire
IC_Downed Tree
IC_Elevator Emergency
IC_Factory Fire
IC_Hospital Fire
IC_Manhole Fire
IC_Maritime Emergency
IC_Maritime Fire
IC_Medical
IC_Medical MFA
IC_Multiple Dwelling A
IC_Multiple Dwelling 'B' Fire
IC_Non-Medical 10-91 (Unnecessary Alarm)
IC_Non-Medical MFA
IC_Odor
IC_Other Commercial Building Fire
IC_Other Public Building Fire
IC_Other Transportation Fire
IC_Private Dwelling Fire
IC_Remove Civilian
IC_School Fire
IC_Sprinkler System
IC_Store Fire
IC_Theater or TV Studio Fire
IC_Transit System
IC_Transit System Emergency
IC_Undefined Emergency
IC_Undefined Nonstructural Fire
IC_Under Contruction / Vacant Fire
IC_Utility Emergency
IC_Vehicle Accident

In [23]:
df["INCIDENT_CLASSIFICATION2"].value_counts()

INCIDENT_CLASSIFICATION2
Medical                                  108948
Assist Civilian                           15846
Utility Emergency                         15012
Alarm System                              14702
Elevator Emergency                        10683
Odor                                       6861
Non-Medical MFA                            4349
Multiple Dwelling 'A'                      4325
Carbon Monoxide                            3640
Vehicle Accident                           3509
Manhole Fire                               2326
Private Dwelling Fire                      2003
Demolition Debris or Rubbish Fire          1947
Other Commercial Building Fire             1341
Medical MFA                                 677
Sprinkler System                            648
Defective Oil Burner                        516
Downed Tree                                 459
Multiple Dwelling 'B' Fire                  451
Automobile Fire                             365
Brush Fire                                  240
Undefined Emergency                         238
School Fire                                 149
Non-Medical 10-91 (Unnecessary Alarm)       135
Remove Civilian                              74
Other Transportation Fire                    64
Hospital Fire                                59
Store Fire                                   42
Church Fire                                  34
Other Public Building Fire                   25
Under Contruction / Vacant Fire              17
Transit System                               15
Abandoned Derelict Vehicle Fire              13
Maritime Emergency                           12
Transit System Emergency                      8
Factory Fire                                  5
Theater or TV Studio Fire                     4
Undefined Nonstructural Fire                  1
Maritime Fire                                 1
Name: count, dtype: int64

In [21]:
df.dtypes

STARFIRE_INCIDENT_ID               object
INCIDENT_DATETIME                  object
ALARM_BOX_BOROUGH                  object
ALARM_BOX_NUMBER                    int64
ALARM_BOX_LOCATION                 object
INCIDENT_BOROUGH                   object
ZIPCODE                           float64
POLICEPRECINCT                    float64
CITYCOUNCILDISTRICT               float64
COMMUNITYDISTRICT                  object
COMMUNITYSCHOOLDISTRICT           float64
CONGRESSIONALDISTRICT             float64
ALARM_SOURCE_DESCRIPTION_TX        object
ALARM_LEVEL_INDEX_DESCRIPTION      object
HIGHEST_ALARM_LEVEL                object
INCIDENT_CLASSIFICATION            object
INCIDENT_CLASSIFICATION_GROUP      object
DISPATCH_RESPONSE_SECONDS_QY       object
FIRST_ASSIGNMENT_DATETIME          object
FIRST_ACTIVATION_DATETIME          object
FIRST_ON_SCENE_DATETIME            object
INCIDENT_CLOSE_DATETIME            object
VALID_DISPATCH_RSPNS_TIME_INDC     object
VALID_INCIDENT_RSPNS_TIME_INDC     object
INCIDENT_RESPONSE_SECONDS_QY       object
INCIDENT_TRAVEL_TM_SECONDS_QY      object
ENGINES_ASSIGNED_QUANTITY         float64
LADDERS_ASSIGNED_QUANTITY         float64
OTHER_UNITS_ASSIGNED_QUANTITY     float64
INCIDENT_CLASSIFICATION2           object
dtype: object

In [9]:
df["INCIDENT_CLASSIFICATION"]

0                  Assist Civilian - Non-Medical
1                       Medical - EMS Link 10-91
2                       Medical - EMS Link 10-91
3         Medical - No PT Contact EMS is Onscene
4         Medical - No PT Contact EMS is Onscene
                           ...
199739                  Medical - EMS Link 10-91
199740    Medical - No PT Contact EMS is Onscene
199741                  Medical - EMS Link 10-91
199742                  Medical - EMS Link 10-91
199743             Elevator Emergency - Occupied
Name: INCIDENT_CLASSIFICATION, Length: 199744, dtype: object

In [45]:
icg = sorted(list(set(df["INCIDENT_CLASSIFICATION_GROUP"].tolist() )))
icg

['Medical Emergencies',
 'Medical MFAs',
 'NonMedical Emergencies',
 'NonMedical MFAs',
 'NonStructural Fires',
 'Structural Fires']

In [89]:
df.dtypes

STARFIRE_INCIDENT_ID               object
INCIDENT_DATETIME                  object
ALARM_BOX_BOROUGH                  object
ALARM_BOX_NUMBER                    int64
ALARM_BOX_LOCATION                 object
INCIDENT_BOROUGH                   object
ZIPCODE                           float64
POLICEPRECINCT                    float64
CITYCOUNCILDISTRICT               float64
COMMUNITYDISTRICT                  object
COMMUNITYSCHOOLDISTRICT           float64
CONGRESSIONALDISTRICT             float64
ALARM_SOURCE_DESCRIPTION_TX        object
ALARM_LEVEL_INDEX_DESCRIPTION      object
HIGHEST_ALARM_LEVEL                object
INCIDENT_CLASSIFICATION            object
INCIDENT_CLASSIFICATION_GROUP      object
DISPATCH_RESPONSE_SECONDS_QY       object
FIRST_ASSIGNMENT_DATETIME          object
FIRST_ACTIVATION_DATETIME          object
FIRST_ON_SCENE_DATETIME            object
INCIDENT_CLOSE_DATETIME            object
VALID_DISPATCH_RSPNS_TIME_INDC     object
VALID_INCIDENT_RSPNS_TIME_INDC     object
INCIDENT_RESPONSE_SECONDS_QY       object
INCIDENT_TRAVEL_TM_SECONDS_QY      object
ENGINES_ASSIGNED_QUANTITY         float64
LADDERS_ASSIGNED_QUANTITY         float64
OTHER_UNITS_ASSIGNED_QUANTITY     float64
Count                               int64
INCIDENT_CLASSIFICATION2           object
dtype: object